### ISSUE TITLE
EPIC: Schemas 1.0

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/schemas#2]
- [ ] Migrate OS schemas to this project
- [ ] Separate geojson validation concerns
- [ ] Add schemas between CI and PSI
