### ISSUE TITLE
Update DefaultParser to accommodate partial Discovery objects

### ISSUE THREAD

**Issue by ajakz** [cedardevs/schemas#23]
### Background
PSI input may sometimes be a hodgepodge of file details and limited discovery details (e.g., just time and space coordinates provided in Discovery). All together this is often enough to be OneStop ready, but the current implementation of the DefaultParser doesn't append to any existing details, it just overwrites the record. This kind of combination of information won't validate properly in OS as written.

### Goal
DefaultParser should assess an existing Discovery block, if present, and update the basic fields if they are not populated.

### Tasks
- [x] Update DefaultParser logic to look at Discovery object
- [x] If any field DefaultParser currently overwrites doesn't exist in the given Discovery, add it with current logic
- [x] Update tests to show the a limited Discovery is enhanced
