### ISSUE TITLE
Add support for YYYY-MM format in temporal bounding input

### ISSUE THREAD

**Issue by ajakz** [cedardevs/schemas#29]
## Background
Some collections in the NOAA data catalog have their temporal boundings defined in `YYYY-MM` format. This is considered a perfectly valid format that we need to support.

## Tasks
- [x] Update the analysis code to handle `YYYY-MM` formatted dates. 
  - In the same manner that we treat year-only dates, our generated UTC timestamps will assume the first second of the month for start dates and the last second of the month for end dates. 
  - See the associated feedback repo issue for more insight: cedardevs/feedback#12.
- [x] When creating the UTC timestamp, add millisecond accuracy (the supported precision in ES) -- so end times should be 23:59:59.999
- [x] Update test cases around this code
- [ ] ~Update any docs referencing accepted formats~ (nothing currently references this, but the metadata to ui TBD doc should)
